// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCyOA-ywVmRCptj-hXxk7pJk2wc5EZPOs',
    appId: '1:492032877063:web:3e957d25f282da199cc0a2',
    messagingSenderId: '492032877063',
    projectId: 'colorviu-b2244',
    authDomain: 'colorviu-b2244.firebaseapp.com',
    storageBucket: 'colorviu-b2244.appspot.com',
    measurementId: 'G-ST12B35S5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtkwvk1CFp2nR4R8pYk3Pj5wZ2JVl77x0',
    appId: '1:492032877063:android:c4348943d6e472ad9cc0a2',
    messagingSenderId: '492032877063',
    projectId: 'colorviu-b2244',
    storageBucket: 'colorviu-b2244.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNZKw4aTy7SPUUUvPa1k6FYfqvMhPU6Dc',
    appId: '1:492032877063:ios:3ff0444ff27199719cc0a2',
    messagingSenderId: '492032877063',
    projectId: 'colorviu-b2244',
    storageBucket: 'colorviu-b2244.appspot.com',
    iosClientId: '492032877063-jd56qr610plrlb7tckju0mndhutvghdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorviu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNZKw4aTy7SPUUUvPa1k6FYfqvMhPU6Dc',
    appId: '1:492032877063:ios:3ff0444ff27199719cc0a2',
    messagingSenderId: '492032877063',
    projectId: 'colorviu-b2244',
    storageBucket: 'colorviu-b2244.appspot.com',
    iosClientId: '492032877063-jd56qr610plrlb7tckju0mndhutvghdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorviu',
  );
}
